INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "AT&T Wireless", 684.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "Verizon FiOS", 111.84]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "NetFlix", 21.87]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "DirecTV", 126.44]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "Washington Gas", 212.13]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "Baltimore Gas & Electric", 212.13]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "Volvo Financial Services", 730.24]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "GM Finance", 645.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "GM Finance", 727.92]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "LinkedIn Subscription", 74.89]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "Digital Ocean: Container Host - Websites", 74.89]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "GreenSky: Front Door Replacement", 1000.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "YouTube Premium: Acct1", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "YouTube Premium: Acct2", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "YouTube Premium: Acct3", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "iCloud+ with 2TB of Storage", 17.15]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "Disney+, Hulu Premium", 31.53]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "Apple One Premier", 41.27]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "Truegreen", 84.34]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('beginner', '["Household Income", "T-Mobile", 74.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "AT&T Wireless", 684.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Verizon FiOS", 111.84]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "NetFlix", 21.87]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "DirecTV", 126.44]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Washington Gas", 212.13]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Baltimore Gas & Electric", 212.13]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Volvo Financial Services", 730.24]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "GM Finance", 645.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "GM Finance", 727.92]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "LinkedIn Subscription", 74.89]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Digital Ocean: Container Host - Websites", 74.89]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "GreenSky: Front Door Replacement", 1000.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "YouTube Premium: Acct1", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "YouTube Premium: Acct2", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "YouTube Premium: Acct3", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "iCloud+ with 2TB of Storage", 17.15]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Disney+, Hulu Premium", 31.53]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Apple One Premier", 41.27]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Truegreen", 84.34]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "T-Mobile", 74.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Truist One Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Bank of America Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Capital One Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Wells Fargo Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "US Bank Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Citi Bank Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "Navy Federal Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "SECU Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "NWFCU Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('intermediate', '["Household Income", "SDFCU Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "AT&T Wireless", 684.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Verizon FiOS", 111.84]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "NetFlix", 21.87]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "DirecTV", 126.44]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Washington Gas", 212.13]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Baltimore Gas & Electric", 212.13]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Volvo Financial Services", 730.24]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "GM Finance", 645.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "GM Finance", 727.92]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "LinkedIn Subscription", 74.89]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Digital Ocean: Container Host - Websites", 74.89]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "GreenSky: Front Door Replacement", 1000.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "YouTube Premium: Acct1", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "YouTube Premium: Acct2", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "YouTube Premium: Acct3", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "iCloud+ with 2TB of Storage", 17.15]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Disney+, Hulu Premium", 31.53]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Apple One Premier", 41.27]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Truegreen", 84.34]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "T-Mobile", 74.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Truist One Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Bank of America Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Capital One Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Wells Fargo Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "US Bank Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Citi Bank Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Navy Federal Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "SECU Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "NWFCU Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "SDFCU Savings", 100.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Wealthfront Cash Management", 500.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Fidelity Cash Management", 500.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "SoFi Savings", 500.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "PayPal Savings", 500.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Credit Karma Savings", 500.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Discover Savings", 500.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('advanced', '["Household Income", "Apple Card Savings", 500.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "AT&T Wireless", 684.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "Verizon FiOS", 111.84]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "NetFlix", 21.87]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "DirecTV", 126.44]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "Washington Gas", 212.13]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "Baltimore Gas & Electric", 212.13]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "Volvo Financial Services", 730.24]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "GM Finance", 645.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "GM Finance", 727.92]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "LinkedIn Subscription", 74.89]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "Digital Ocean: Container Host - Websites", 74.89]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "GreenSky: Front Door Replacement", 1000.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "YouTube Premium: Acct1", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "YouTube Premium: Acct2", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "YouTube Premium: Acct3", 30.00]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "iCloud+ with 2TB of Storage", 17.15]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "Disney+, Hulu Premium", 31.53]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "Apple One Premier", 41.27]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "Truegreen", 84.34]');
INSERT INTO diag_data (level_id, recordSet) VALUES ('expert', '["Household Income", "T-Mobile", 74.00]');
